version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8889:8889
    depends_on: 
      - mysql_server
    network_mode: host
  
  mysql_server:
    image: mysql
    environment: 
      - MYSQL_DATABASE=movie_ticket
      - MYSQL_ROOT_PASSWORD=password
    ports:
     - 3306:3306
    network_mode: host
