version: "3.8"

networks:
  backend:

services: 
  app1:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8889:8889
    depends_on: 
      - mysql_server
    restart: always
    networks: 
      - backend
  
  mysql_server:
    image: mysql
    environment: 
      - MYSQL_DATABASE=storedata
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    restart: always
    networks: 
      - backend
